"use client";
import {useState} from "react";
import {useLab,useAnalysis} from "../lab-context";
import {PageHeading,FilterBar,VariableSelect,Metric,ChartCard,Status,InfoBox} from "../shared";
import {Histogram,BoxPlot,CategoryChart} from "../charts";
import {Card} from "../ui/card";
import {Input,Label,Select} from "../ui/input";
import {number,precise} from "@/lib/utils";
import type {Descriptive,Bin} from "@/lib/types";
export function FrequencyTable({bins}:{bins:Bin[]}){return <div className="table-wrap" style={{maxHeight:370}}><table className="data-table"><thead><tr><th>Classe</th><th className="numeric">Frequência</th><th className="numeric">Relativa</th><th className="numeric">Acumulada</th><th className="numeric">Rel. acumulada</th></tr></thead><tbody>{bins.map((bin,index)=><tr key={index}><td className="mono nowrap">[{number(bin.inferior,4)}; {number(bin.superior,4)}{index===bins.length-1?"]":")"}</td><td className="numeric">{number(bin.frequencia,0)}</td><td className="numeric">{number(bin.relativa*100,4)}%</td><td className="numeric">{number(bin.acumulada,0)}</td><td className="numeric">{number(bin.relativa_acumulada*100,4)}%</td></tr>)}</tbody></table></div>;}
/** Todas as medidas e frequências vêm da biblioteca própria no servidor. */
export function DescriptivePage(){const {filters}=useLab();const [variable,setVariable]=useState("quantidade_pagador_pf"),[bins,setBins]=useState(25),[sample,setSample]=useState(false),[percentile,setPercentile]=useState(90),[pie,setPie]=useState(false);
 const query=useAnalysis<Descriptive>("descritiva",{...filters,variavel:variable,classes:bins,amostral:sample,percentual:percentile});const data=query.data?.resultado;
 return <><PageHeading title="Estatística Descritiva" description="Explore o comportamento de uma variável: centro, dispersão, forma e observações atípicas. Da fórmula ao dado, sem caixas-pretas."/><FilterBar/>
 <Card className="control-card"><div className="controls"><VariableSelect value={variable} onChange={setVariable} categories/><div className="control-field small-field"><Label htmlFor="classes">Faixas do gráfico</Label><Select id="classes" value={bins} onChange={event=>setBins(Number(event.target.value))}>{[5,10,15,20,25,40,50,80,100].map(value=><option key={value}>{value}</option>)}</Select></div><div className="control-field small-field"><Label htmlFor="convencao">Tipo de análise</Label><Select id="convencao" value={sample?"amostral":"populacional"} onChange={event=>setSample(event.target.value==="amostral")}><option value="populacional">Todo o recorte</option><option value="amostral">Como amostra</option></Select></div><div className="control-field small-field"><Label htmlFor="percentil">Percentil adicional</Label><Input type="number" id="percentil" min={0} max={100} step={1} value={percentile} onChange={event=>{const value=Number(event.target.value);if(value>=0&&value<=100)setPercentile(value);}}/></div></div></Card>
 <Status {...query} onRetry={query.retry}/>{data&&!query.loading&&!query.error&&(data.tipo==="numerica"?<>
 <div className="metrics-grid"><Metric label="Média" value={precise(data.medidas.media)} hint="Soma dos valores ÷ n"/><Metric label="Mediana" value={precise(data.medidas.mediana)} hint="Percentil 50 da distribuição"/><Metric label="Desvio padrão" value={precise(data.medidas.desvio_padrao)} hint={sample?"Estimador amostral (n − 1)":"Universo filtrado (n)"}/><Metric label="Coef. de variação" value={data.medidas.coeficiente_variacao===null?"Indefinido":`${precise(data.medidas.coeficiente_variacao)}%`} hint="Dispersão relativa à média absoluta" accent/></div>
 <div className="metrics-grid six"><Metric label="Q1 · 25%" value={precise(data.medidas.q1)}/><Metric label="Q2 · 50%" value={precise(data.medidas.q2)}/><Metric label="Q3 · 75%" value={precise(data.medidas.q3)}/><Metric label="IQR" value={precise(data.medidas.iqr)} hint="Q3 − Q1"/><Metric label="Amplitude" value={precise(data.medidas.amplitude)}/><Metric label="Atípicos" value={number(data.medidas.atipicos,0)} hint="Regra 1,5 × IQR"/></div>
 <div className="analysis-layout"><div className="stack"><ChartCard title="Distribuição da variável" subtitle={data.variavel.rotulo} action={<span className="badge badge-neutral">{bins} classes</span>}><Histogram bins={data.frequencias}/></ChartCard><ChartCard title="Boxplot e detecção de atípicos" subtitle="Observações preservadas na análise"><BoxPlot box={data.caixa}/></ChartCard></div><div className="stack"><ChartCard title="Detalhes do cálculo"><dl className="parameter-list"><dt>n válido</dt><dd>{number(data.medidas.quantidade,0)}</dd><dt>Ausentes excluídos</dt><dd>{data.ausentes_excluidos}</dd><dt>Mínimo</dt><dd>{precise(data.medidas.minimo)}</dd><dt>Máximo</dt><dd>{precise(data.medidas.maximo)}</dd><dt>Variância</dt><dd>{precise(data.medidas.variancia)}</dd><dt>Assimetria g₁</dt><dd>{precise(data.medidas.assimetria)}</dd><dt>Percentil {percentile}</dt><dd>{precise(data.percentil.valor)}</dd></dl><hr/><p className="small muted">Moda: {data.medidas.modas.length?data.medidas.modas.map(value=>number(value,4)).join(", "):"Amodal: nenhum valor se repete."}{data.medidas.numero_modas>50?` (${data.medidas.numero_modas} modas; primeiras 50 exibidas.)`:""}</p></ChartCard><InfoBox title="Leitura automática">{data.medidas.interpretacao}</InfoBox>{data.medidas.avisos.map(warning=><InfoBox key={warning} tone="warning">{warning}</InfoBox>)}</div></div>
 <ChartCard title="Distribuição de frequências" subtitle="Intervalos fechados à esquerda; somente a última classe inclui o limite superior." className="section-space"><FrequencyTable bins={data.frequencias}/></ChartCard>
 </>:<><InfoBox title="Variável categórica">{data.interpretacao} Média, variância e quartis não se aplicam a categorias nominais.</InfoBox><ChartCard title="Frequência por categoria" className="section-space" action={<div className="segmented"><button className={!pie?"active":""} onClick={()=>setPie(false)}>Barras</button><button className={pie?"active":""} onClick={()=>setPie(true)}>Pizza</button></div>}><CategoryChart data={data.frequencias} pie={pie}/></ChartCard><ChartCard title="Tabela de frequências" className="section-space"><div className="table-wrap" style={{maxHeight:450}}><table className="data-table"><thead><tr><th>Categoria</th><th className="numeric">Frequência</th><th className="numeric">Relativa</th></tr></thead><tbody>{data.frequencias.map(row=><tr key={row.categoria}><td>{row.categoria}</td><td className="numeric">{number(row.frequencia,0)}</td><td className="numeric">{number(row.relativa*100,3)}%</td></tr>)}</tbody></table></div></ChartCard></>)}</>;
}
