"use client";
import {useState} from "react";
import {useLab,useAnalysis} from "../lab-context";
import {PageHeading,FilterBar,VariableSelect,ChartCard,Status,InfoBox} from "../shared";
import {Card} from "../ui/card";
import {Label,Select} from "../ui/input";
import {Histogram,MassChart} from "../charts";
import {precise} from "@/lib/utils";
import {FrequencyTable} from "./descriptive";
import type {Distribution} from "@/lib/types";
const names:Record<string,string>={normal:"Normal",exponencial:"Exponencial",uniforme:"Uniforme",poisson:"Poisson"};
const params:Record<string,string>={media:"μ · média",desvio_populacional:"σ · desvio",taxa:"λ · taxa",intensidade:"λ · intensidade",inferior:"a · limite inferior",superior:"b · limite superior"};
export function DistributionPage(){const {filters}=useLab();const [variable,setVariable]=useState("valor_pagador_pf"),[family,setFamily]=useState("normal"),[bins,setBins]=useState(30);const query=useAnalysis<Distribution>("distribuicoes",{...filters,variavel:variable,distribuicao:family,classes:bins});const data=query.data?.resultado;
 return <><PageHeading title="Distribuições Teóricas" description="Confronte o dado observado com um modelo probabilístico. Um ajuste ruim também é um resultado importante."/><FilterBar/><Card className="control-card"><div className="controls"><VariableSelect value={variable} onChange={setVariable}/><div className="control-field"><Label htmlFor="distribuicao">Distribuição candidata</Label><Select id="distribuicao" value={family} onChange={event=>setFamily(event.target.value)}>{Object.entries(names).map(([key,value])=><option key={key} value={key}>{value}</option>)}</Select></div><div className="control-field small-field"><Label htmlFor="classes-ajuste">Classes</Label><Select id="classes-ajuste" value={bins} onChange={event=>setBins(Number(event.target.value))}>{[10,20,30,50,80,100].map(value=><option key={value}>{value}</option>)}</Select></div></div><p className="control-note">Normal e Exponencial permitem comparar modelos contínuos. Poisson exige contagens inteiras não negativas e utiliza massa de probabilidade.</p></Card>
 <Status {...query} onRetry={query.retry}/>{data&&!query.loading&&!query.error&&<><div className="analysis-layout"><ChartCard title={`Dados observados × ${names[data.distribuicao]}`} subtitle={data.tipo==="continua"?"Histograma normalizado por largura da classe; curva em densidade, na mesma escala.":"Frequências relativas observadas e probabilidades teóricas nos inteiros."}>{data.tipo==="continua"?<Histogram bins={data.histograma} curve={data.curva} density/>:<MassChart data={data}/>}<p className="chart-caption">A curva é uma candidata, não um modelo confirmado. Compare o centro, a cauda e a dispersão; não apenas a proximidade de um ponto.</p></ChartCard><div className="stack"><ChartCard title="Parâmetros estimados" subtitle="Estimativas calculadas pelo núcleo próprio"><dl className="parameter-list">{Object.entries(data.parametros).map(([key,value])=><div key={key} style={{display:"contents"}}><dt>{params[key]??key}</dt><dd>{precise(value)}</dd></div>)}{data.tipo==="discreta"&&<><dt>Variância / média</dt><dd>{precise(data.dispersao_media)}</dd></>}</dl></ChartCard><InfoBox title="Leitura do ajuste">{data.tipo==="discreta"?"A Poisson pressupõe média e variância iguais. Valores municipais heterogêneos podem apresentar dispersão muito maior; isso não invalida os dados.":"Municípios de portes distintos podem gerar uma cauda longa que uma distribuição simples não representa. A Normal ainda atribui probabilidade a valores negativos, impossíveis para estes fluxos."}</InfoBox></div></div><div className="stack section-space">{data.avisos.map(warning=><InfoBox key={warning} tone="warning">{warning}</InfoBox>)}</div><ChartCard title="Valores do histograma observado" subtitle="Mesma discretização utilizada na visualização contínua." className="section-space"><FrequencyTable bins={data.histograma}/></ChartCard></>}</>;
}
