"use client";
import Link from "next/link";
import {BookOpen,Database,ExternalLink} from "../ui/icons";
import {useLab,useAnalysis} from "../lab-context";
import {PageHeading,FilterBar,Metric,ChartCard,Status,InfoBox,ExportButton} from "../shared";
import {Card,CardContent} from "../ui/card";
import type {Finding} from "@/lib/types";
const sections=[
 {id:"media",title:"Média aritmética",formula:"x̄ = (1/n) ∑ xᵢ",text:"Soma os valores finitos com soma compensada (math.fsum) e divide por n. A operação de soma é elementar, não uma medida estatística pronta.",code:"media(valores)"},
 {id:"mediana",title:"Mediana",formula:"mediana = P₅₀",text:"Valor central da sequência ordenada; em tamanho par, média dos dois elementos centrais. Implementada pela mesma convenção de percentis.",code:"mediana(valores)"},
 {id:"moda",title:"Moda e multimodalidade",formula:"M = {x : frequência(x) = frequência máxima}",text:"Retorna todas as modas em ordem. Convenção declarada: quando todos os valores ocorrem uma vez, retorna lista vazia (amodal). Nenhum desempate arbitrário.",code:"moda(valores)"},
 {id:"variancia",title:"Variância e desvio padrão",formula:"σ² = ∑(xᵢ − x̄)²/n    |    s² = ∑(xᵢ − x̄)²/(n − 1)",text:"Implementação em duas passagens para reduzir cancelamento numérico. Desvio padrão é a raiz da variância. A versão amostral exige n ≥ 2; a populacional descreve o universo filtrado.",code:"variancia(valores, amostral=True); desvio_padrao(valores, amostral=True)"},
 {id:"quantis",title:"Quartis e percentis",formula:"h = (n − 1)p/100; j = ⌊h⌋; Pₚ = x₍ⱼ₎ + (h − j)(x₍ⱼ₊₁₎ − x₍ⱼ₎)",text:"Interpolação linear tipo 7, equivalente a numpy.percentile(method='linear'). Índices começam em zero. Q1 = P25, Q2 = P50 e Q3 = P75; extremos p=0/100 são tratados diretamente.",code:"percentil(valores, percentual); quartis(valores)"},
 {id:"dispersao",title:"Amplitude e coeficiente de variação",formula:"A = máximo − mínimo    |    CV = 100 × desvio / |média|",text:"CV é percentual e fica indefinido com média zero. A convenção de valor absoluto é explícita; seu uso faz sentido sobretudo em escalas de razão, como contagens e valores positivos.",code:"amplitude(valores); coeficiente_variacao(valores, amostral=True)"},
 {id:"covariancia",title:"Covariância e Pearson",formula:"cov(X,Y) = ∑(xᵢ − x̄)(yᵢ − ȳ)/(n − 1); r = Sxy / √(Sxx Syy)",text:"Pares são preservados. No serviço, um par com ausência em X ou Y é excluído conjuntamente e contado. Pearson fica indefinido se uma das variáveis for constante.",code:"covariancia(x, y, amostral=True); correlacao_pearson(x, y)"},
 {id:"regressao",title:"Regressão linear por mínimos quadrados",formula:"β₁ = Sxy/Sxx; β₀ = ȳ − β₁x̄; ŷ = β₀ + β₁x",text:"A reta minimiza a soma dos quadrados dos resíduos verticais. X constante impede estimar a inclinação. Predições fora do domínio observado são sinalizadas, nunca disfarçadas como certezas.",code:"regressao_linear(x, y); predizer(x, intercepto, inclinacao)"},
 {id:"r2",title:"Coeficiente de determinação",formula:"R² = 1 − ∑(yᵢ − ŷᵢ)² / ∑(yᵢ − ȳ)²",text:"Calculado pelos resíduos, não copiado do quadrado de Pearson. Y constante torna o denominador zero: retorna indefinido. Em regressão simples com intercepto, r² e R² coincidem (caso não degenerado).",code:"coeficiente_determinacao(observados, previstos)"},
 {id:"iqr",title:"Regra do IQR e assimetria",formula:"IQR = Q3 − Q1; limites = [Q1 − 1,5 IQR; Q3 + 1,5 IQR]",text:"Atípicos são marcados, não removidos. Bigodes são valores observados dentro dos limites. A interpretação usa o terceiro momento padronizado populacional g1; média maior que mediana, isoladamente, não basta.",code:"detectar_atipicos(valores); assimetria(valores)"},
 {id:"probabilidade",title:"Simulação de Monte Carlo",formula:"fₙ = acertos/n    |    E(X̄) = μ; DP(X̄) = σ/√n",text:"Gerador pseudoaleatório local com semente. TCL: sorteios independentes com reposição da distribuição empírica do recorte. O erro padrão teórico usa o desvio populacional. A simulação não demonstra representatividade de pessoas ou causalidade.",code:"simular_grandes_numeros(...); simular_limite_central(...)"},
 {id:"distribuicoes",title:"Distribuições e escala dos gráficos",formula:"Normal: (μ,σ)    |    Exponencial: λ = 1/x̄    |    Poisson: λ = x̄",text:"Normal usa média e desvio populacional; Uniforme usa mínimo e máximo. PDF contínua é sobreposta a histograma de densidade. Poisson é massa discreta, desenhada em inteiros e comparada à frequência relativa. Não há selo automático de bom ajuste.",code:"densidade_normal; densidade_exponencial; densidade_uniforme; massa_poisson"}
];
export function MethodologyPage(){return <><PageHeading eyebrow="COMO INTERPRETAR" title="Metodologia" description="Conheça as ideias por trás de cada análise e entenda o que os resultados significam."/><div className="docs-layout"><nav className="docs-toc" aria-label="Sumário da metodologia"><span className="mini-label">Nesta página</span>{sections.map(section=><a href={`#${section.id}`} key={section.id}>{section.title}</a>)}</nav><div><InfoBox title="Resultados verificados" tone="success">As medidas apresentadas pelo observatório são conferidas automaticamente para garantir resultados consistentes.</InfoBox><div className="section-space">{sections.map(section=><Card id={section.id} key={section.id} className="docs-section"><CardContent style={{padding:24}}><div className="inline"><BookOpen size={15}/><h2>{section.title}</h2></div><div className="formula">{section.formula}</div><p>{section.text}</p></CardContent></Card>)}</div></div></div></>;}
export function SourcesPage(){return <><PageHeading eyebrow="DADOS PÚBLICOS" title="Sobre os Dados" description="Entenda de onde vêm os números e como interpretá-los com segurança."/><div className="source-hero"><Database size={40}/><div><span className="mini-label" style={{color:"inherit"}}>Fonte oficial</span><h2>Banco Central do Brasil</h2><p>Estatísticas mensais do Pix por município</p><a href="https://dadosabertos.bcb.gov.br/dataset/pix" target="_blank" rel="noreferrer" className="inline small">Conhecer a fonte original <ExternalLink size={13}/></a></div></div><div className="metrics-grid section-space"><Metric label="Abrangência" value="Brasil" hint="Regiões, estados e municípios"/><Metric label="Detalhamento" value="Municipal" hint="Comparações locais e regionais"/><Metric label="Atualização" value="Mensal" hint="Os dados não são em tempo real"/><Metric label="Valores" value="Em reais" hint="Montantes financeiros em R$"/></div><div className="two-columns"><ChartCard title="Como usar estes dados"><div className="interpretation"><p>Escolha um período e uma localidade para explorar a movimentação do Pix.</p><p>Os resultados reúnem valores e quantidades por município, permitindo comparar regiões e acompanhar mudanças ao longo dos meses.</p><p>Os filtros são aplicados igualmente em todas as páginas para facilitar a comparação.</p></div></ChartCard><ChartCard title="O que os números contam"><div className="interpretation"><p>Os dados mostram a movimentação registrada em cada município, mas não revelam renda, riqueza ou hábitos individuais.</p><p>Municípios maiores tendem a concentrar mais transações, por isso o porte de cada local deve ser considerado nas comparações.</p><p>Pagamentos e recebimentos são duas perspectivas do mesmo fluxo e aparecem separadamente.</p></div></ChartCard></div><div className="two-columns section-space"><InfoBox title="Leitura responsável" tone="warning">Use os resultados para identificar padrões e fazer comparações, não para tirar conclusões sobre pessoas específicas ou afirmar relações de causa e efeito.</InfoBox><InfoBox title="Sobre o observatório">Este é um projeto acadêmico independente baseado nos dados públicos do Banco Central do Brasil.</InfoBox></div></>;}

function explicarDescoberta(finding:Finding,index:number){
 const evidence=finding.evidencia as Record<string,number>;
 if(index===0){const share=(evidence.participacao*100).toLocaleString("pt-BR",{maximumFractionDigits:1});return {title:"A movimentação se concentra em poucos municípios",text:`Os 50 municípios com maior volume de pagamentos reúnem ${share}% de todo o valor analisado. Isso mostra como os grandes centros têm um peso muito maior no total nacional.`,note:"Esse resultado fala sobre movimentação financeira local, não sobre a renda ou a riqueza dos moradores."};}
 if(index===1){const ratio=evidence.razao.toLocaleString("pt-BR",{maximumFractionDigits:1});return {title:"Os maiores municípios puxam a média para cima",text:`A média de transações ficou ${ratio} vezes acima da mediana. Em outras palavras, poucos municípios com volumes muito altos elevam bastante a média geral.`,note:"A mediana representa melhor o município típico quando os valores são tão diferentes entre si."};}
 const strength=Math.abs(evidence.pearson).toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2});return {title:"Mais transações costumam vir acompanhadas de maior valor",text:`A relação observada é forte (${strength} em uma escala que vai até 1): municípios com mais transações geralmente também movimentam mais dinheiro.`,note:"Isso é uma associação, não uma prova de que uma coisa cause a outra. O tamanho do município influencia os dois números."};
}
export function FindingsPage(){const {filters}=useLab();const query=useAnalysis<Finding[]>("descobertas",filters);return <><PageHeading title="Descobertas Estatísticas" description="Três leituras simples para entender o que mais chama atenção no período selecionado." eyebrow="DESTAQUES DO PERÍODO" actions={<ExportButton report/>}/><FilterBar/><Status {...query} onRetry={query.retry}/><div className="stack section-space">{query.data&&!query.loading&&!query.error&&query.data.resultado.map((finding,index)=>{const friendly=explicarDescoberta(finding,index);return <Card key={finding.titulo} className="finding"><div className="finding-index">0{index+1}</div><div><span className="badge badge-neutral">O que os dados mostram</span><h2 style={{marginTop:12}}>{friendly.title}</h2><p>{friendly.text}</p><InfoBox title="Como interpretar">{friendly.note}</InfoBox><div className="inline section-space"><Link className="source-link" href={finding.grafico}>Ver análise relacionada →</Link></div></div></Card>;})}</div></>;}
