"use client";
import {useState,useEffect} from "react";
import {ArrowDownUp,ChevronLeft,ChevronRight,Search} from "../ui/icons";
import {useLab,useAnalysis} from "../lab-context";
import {PageHeading,FilterBar,Status,Empty,ExportButton,InfoBox} from "../shared";
import {Input,Select} from "../ui/input";
import {Button} from "../ui/button";
import {Card} from "../ui/card";
import {number,period,money} from "@/lib/utils";
import type {Rows} from "@/lib/types";
/** Paginação, busca e ordenação executadas na API. */
export function ExplorerPage(){
 const {filters,catalog}=useLab();const [page,setPage]=useState(1),[size,setSize]=useState(25),[search,setSearch]=useState(""),[draft,setDraft]=useState(""),[sort,setSort]=useState("valor_pagador_pf"),[descending,setDescending]=useState(true),[columns,setColumns]=useState(["valor_pagador_pf","quantidade_pagador_pf","valor_pagador_pj","quantidade_pagador_pj"]);
 const filterKey=JSON.stringify(filters);useEffect(()=>setPage(1),[filterKey,search,size]);
 const query=useAnalysis<Rows>("dados",{...filters,pagina:page,tamanho:size,busca:search,ordenar:sort,decrescente:descending});const data=query.data?.resultado;
 function order(key:string){setDescending(key===sort?!descending:false);setSort(key);setPage(1);}
 return <><PageHeading eyebrow="OBSERVATÓRIO PÚBLICO" title="Explorar Dados" description="O dado por trás do gráfico. Consulte, ordene e exporte as observações municipais usadas nas análises." actions={<ExportButton/>}/><FilterBar/>
 <InfoBox title="Uma linha = um município em um mês">Códigos geográficos são identificadores, não variáveis quantitativas. A exportação CSV contém todas as linhas do recorte temporal e geográfico, não apenas a página ou a busca de texto.</InfoBox>
 <Card className="section-space"><div className="table-toolbar"><form className="inline" onSubmit={event=>{event.preventDefault();setSearch(draft);setPage(1);}}><label className="sr-only" htmlFor="busca">Buscar município ou UF</label><Input id="busca" placeholder="Buscar município ou UF..." value={draft} onChange={event=>setDraft(event.target.value)}/><Button type="submit" variant="outline" size="icon" aria-label="Buscar"><Search size={15}/></Button></form><div className="inline"><span className="small muted">{data?`${number(data.total,0)} registros encontrados`:"Consultando..."}</span><details className="table-details"><summary>Colunas visíveis</summary><div className="column-menu">{Object.entries(catalog?.numericas??{}).map(([key,definition])=><label key={key}><input type="checkbox" checked={columns.includes(key)} onChange={event=>setColumns(event.target.checked?[...columns,key]:columns.filter(column=>column!==key))}/>{definition.rotulo}</label>)}</div></details></div></div>
 <Status {...query} onRetry={query.retry}/>{data&&!query.loading&&!query.error&&(data.total===0?<Empty/>:<><div className="table-wrap"><table className="data-table"><thead><tr>{[["competencia","Período"],["municipio","Município"],["uf","UF"],["regiao","Região"],...columns.map(key=>[key,catalog?.numericas[key]?.rotulo??key])].map(([key,label])=><th key={key} aria-sort={sort===key?(descending?"descending":"ascending"):"none"}><button onClick={()=>order(key)}>{label}<ArrowDownUp size={11}/></button></th>)}</tr></thead><tbody>{data.linhas.map(row=><tr key={`${row.competencia}-${row.codigo_municipio}`}><td className="nowrap">{period(row.competencia)}</td><td className="nowrap"><strong>{row.municipio}</strong><div className="muted small">IBGE {row.codigo_municipio}</div></td><td>{row.uf}</td><td className="nowrap">{row.regiao}</td>{columns.map(column=><td className="numeric" key={column}>{row[column]===null?"Ausente":column.startsWith("valor_")?money(Number(row[column])):number(Number(row[column]),0)}</td>)}</tr>)}</tbody></table></div><div className="pagination"><div className="inline"><span>Linhas por página</span><Select aria-label="Linhas por página" value={size} style={{width:75}} onChange={event=>setSize(Number(event.target.value))}>{[10,25,50,100].map(value=><option key={value}>{value}</option>)}</Select></div><div className="inline"><span>Página {page} de {data.paginas}</span><Button variant="outline" size="icon" disabled={page<=1} onClick={()=>setPage(page-1)} aria-label="Página anterior"><ChevronLeft size={15}/></Button><Button variant="outline" size="icon" disabled={page>=data.paginas} onClick={()=>setPage(page+1)} aria-label="Próxima página"><ChevronRight size={15}/></Button></div></div></>)}</Card></>;
}
