"use client";
import {useState} from "react";
import Link from "next/link";
import {ArrowUpRight,Wallet,ArrowLeftRight,MapPin,Receipt,Lightbulb} from "../ui/icons";
import {useLab,useAnalysis} from "../lab-context";
import {PageHeading,FilterBar,Metric,ChartCard,Status,Empty,InfoBox,ShareButton} from "../shared";
import {Select,Label} from "../ui/input";
import {EvolutionChart,RegionsChart,PeopleChart} from "../charts";
import {compact,money,number} from "@/lib/utils";
import type {Panorama} from "@/lib/types";
/** Painel público: todos os indicadores são recebidos do núcleo Python. */
export function OverviewPage(){
 const {filters}=useLab();const [role,setRole]=useState("pagador"),[person,setPerson]=useState("todos"),[metric,setMetric]=useState<"valor"|"quantidade">("valor");
 const query=useAnalysis<Panorama>("panorama",{...filters,papel:role,pessoa:person});const data=query.data?.resultado;
 return <><PageHeading eyebrow="DADOS ABERTOS · BRASIL" title="Visão Geral" description="Entenda como o Pix movimenta municípios, estados e regiões. Dados agregados, cálculos transparentes e uma nova perspectiva sobre os números." actions={<ShareButton/>}/><FilterBar/>
 <div className="inline" style={{marginBottom:20}}><div className="filter-item"><Label htmlFor="papel">Perspectiva do fluxo</Label><Select id="papel" value={role} onChange={e=>setRole(e.target.value)}><option value="pagador">Lado pagador</option><option value="recebedor">Lado recebedor</option></Select></div><div className="filter-item"><Label htmlFor="pessoa">Tipo de pessoa</Label><Select id="pessoa" value={person} onChange={e=>setPerson(e.target.value)}><option value="todos">PF + PJ</option><option value="pf">Pessoa Física</option><option value="pj">Pessoa Jurídica</option></Select></div><div className="segmented right" aria-label="Métrica dos gráficos"><button className={metric==="valor"?"active":""} onClick={()=>setMetric("valor")}>Valor movimentado</button><button className={metric==="quantidade"?"active":""} onClick={()=>setMetric("quantidade")}>Transações</button></div></div>
 <Status {...query} onRetry={query.retry}/>{data&&!query.loading&&!query.error&&(query.data!.contexto.registros===0?<Empty/>:<>
 <div className="metrics-grid"><Metric label={role==="pagador"?"Valor pago":"Valor recebido"} value={money(data.totais.valor,true)} hint="Valor nominal no recorte selecionado" icon={<Wallet/>}/><Metric label="Transações" value={compact(data.totais.quantidade)} hint={role==="pagador"?"Perspectiva dos pagadores":"Perspectiva dos recebedores"} icon={<ArrowLeftRight/>}/><Metric label="Ticket médio" value={money(data.totais.ticket_medio)} hint="Valor total ÷ quantidade total" icon={<Receipt/>}/><Metric label="Municípios observados" value={number(query.data!.contexto.municipios,0)} hint={`${number(query.data!.contexto.registros,0)} observações município-mês`} icon={<MapPin/>} accent/></div>
 <div className="dashboard-grid"><ChartCard title="Evolução das transações Pix" subtitle={metric==="valor"?"Valor movimentado por competência (R$)":"Quantidade de transações por competência"} action={<span className="badge badge-neutral">Mensal</span>}><EvolutionChart data={data.meses} metric={metric}/>{data.meses.length===1&&<p className="chart-caption">Um único mês não representa uma tendência. Selecione “2025 completo” para comparar competências.</p>}</ChartCard>
 <ChartCard title="Pix por região" subtitle="Distribuição do fluxo no recorte"><RegionsChart data={data.regioes} metric={metric}/></ChartCard>
 <ChartCard title="Destaques municipais" subtitle="Maiores valores totais na perspectiva selecionada" action={<Link href="/explorar" className="source-link">Explorar<ArrowUpRight size={13}/></Link>}><div className="table-wrap"><table className="data-table"><thead><tr><th>#</th><th>Município</th><th className="numeric">Valor</th><th className="numeric">Transações</th><th className="numeric">Ticket</th></tr></thead><tbody>{data.municipios.slice(0,5).map((row,index)=><tr key={row.codigo_municipio}><td><span className="rank">{index+1}</span></td><td><strong>{row.municipio}</strong><div className="small muted">{row.uf}</div></td><td className="numeric">{money(row.valor,true)}</td><td className="numeric">{compact(row.quantidade)}</td><td className="numeric">{money(row.ticket_medio)}</td></tr>)}</tbody></table></div></ChartCard>
 <ChartCard title="Pessoa Física × Pessoa Jurídica" subtitle="Comparação independente do seletor PF/PJ; mesmo recorte geográfico"><PeopleChart data={data.pessoas} metric={metric}/></ChartCard>
 <div className="insight-card"><div className="inline"><Lightbulb size={17}/><span className="mini-label">Uma leitura dos dados</span></div><div className="insight-number">{data.concentracao.participacao===null?"Indefinido":`${number(data.concentracao.participacao*100)}%`}</div><p>do valor do recorte está nos {data.concentracao.quantidade} municípios com maiores totais. Concentração de movimentação não equivale a renda ou riqueza dos moradores.</p><Link href="/descobertas">Conheça as descobertas estatísticas →</Link></div>
 <InfoBox title="O que estes números representam"><p>{data.aviso}</p><p>Pagadores e recebedores descrevem dois lados dos fluxos: não são somados. Quantidades de pessoas não aparecem como “usuários únicos anuais”.</p><p>{number(data.totais.excluidos,0)} observações excluídas dos totais por campos ausentes.</p></InfoBox></div></>)}</>;
}

