"use client";
import {useState} from "react";
import {Calculator} from "../ui/icons";
import {useLab,useAnalysis} from "../lab-context";
import {PageHeading,FilterBar,VariableSelect,Metric,ChartCard,Status,InfoBox} from "../shared";
import {Card} from "../ui/card";
import {Input,Label} from "../ui/input";
import {Button} from "../ui/button";
import {RegressionChart} from "../charts";
import {number,precise} from "@/lib/utils";
import type {Regression} from "@/lib/types";
export function RegressionPage(){const {filters,catalog}=useLab();const [x,setX]=useState("quantidade_pagador_pf"),[y,setY]=useState("valor_pagador_pf"),[prediction,setPrediction]=useState<number|null>(null),[draft,setDraft]=useState("100000");const query=useAnalysis<Regression>("regressao",{...filters,variavel_x:x,variavel_y:y,valor_predicao:prediction});const data=query.data?.resultado;
 const xLabel=catalog?.numericas[x]?.rotulo??x,yLabel=catalog?.numericas[y]?.rotulo??y;
 return <><PageHeading title="Correlação e Regressão Linear" description="Compare duas características e veja como elas variam juntas nos municípios selecionados."/><FilterBar/><Card className="control-card"><div className="controls"><VariableSelect id="variavel-x" label="Primeira variável" value={x} onChange={value=>{setX(value);setPrediction(null);}}/><VariableSelect id="variavel-y" label="Segunda variável" value={y} onChange={value=>{setY(value);setPrediction(null);}}/></div></Card>
 <Status {...query} onRetry={query.retry}/>{data&&!query.loading&&!query.error&&<><div className="metrics-grid"><Metric label="Correlação de Pearson" value={precise(data.modelo.pearson)} hint={data.modelo.pearson===null?"Uma variável tem dispersão nula":data.modelo.pearson>0?"Associação linear positiva":data.modelo.pearson<0?"Associação linear negativa":"Sem associação linear nesta medida"}/><Metric label="Coef. de determinação R²" value={precise(data.modelo.r_quadrado)} hint="Ajuste dentro da amostra, não acurácia futura" accent/><Metric label="Inclinação β₁" value={precise(data.modelo.inclinacao)} hint="Unidades de Y por unidade de X"/><Metric label="Intercepto β₀" value={precise(data.modelo.intercepto)} hint="Valor ajustado de Y quando X = 0"/></div>
 <div className="analysis-layout"><div className="stack"><ChartCard title="Relação entre as variáveis" subtitle={`X: ${xLabel} · Y: ${yLabel}`}><RegressionChart data={data}/><div className="legend"><span><i/>Município-mês</span><span><i className="theoretical"/>Reta de regressão</span></div><p className="chart-caption">{number(data.modelo.quantidade,0)} pares válidos; {number(data.ausentes_excluidos,0)} excluídos por ausência pareada. {data.amostragem_visual?"Exibição limitada a 2.000 pontos, incluindo extremos; o ajuste usa todos os pares.":"Todos os pares são exibidos."}</p></ChartCard><div className="equation">ŷ = {precise(data.modelo.intercepto)} {data.modelo.inclinacao<0?"−":"+"} {precise(Math.abs(data.modelo.inclinacao))}x</div></div><div className="stack"><ChartCard title="Fazer uma predição" subtitle="Resultado calculado pela API, não no navegador"><form onSubmit={event=>{event.preventDefault();setPrediction(Number(draft));}}><Label htmlFor="predicao">Informe um valor para X</Label><Input id="predicao" type="number" step="any" required value={draft} onChange={event=>setDraft(event.target.value)}/><p className="small muted" style={{margin:"9px 0 13px"}}>Faixa observada: {precise(data.modelo.minimo_x)} a {precise(data.modelo.maximo_x)}.</p><Button type="submit"><Calculator size={14}/>Calcular Ŷ</Button></form>{data.predicao&&<div className="prediction-result"><span className="mini-label">Y estimado</span><p>{precise(data.predicao.valor_y)}</p><span className="small">Para X = {precise(data.predicao.valor_x)}</span></div>}{data.predicao?.extrapolacao&&<div className="section-space"><InfoBox tone="warning">Extrapolação: X está fora do intervalo observado. Esta estimativa exige cautela adicional.</InfoBox></div>}{data.predicao&&data.predicao.valor_y<0&&<p className="small warning-text section-space">A reta produziu valor negativo, incompatível com o domínio desta variável. O resultado não foi truncado artificialmente.</p>}</ChartCard><ChartCard title="Como interpretar"><div className="interpretation"><p>{data.interpretacao}</p><p>R² mede a redução do erro quadrático em relação à média de Y. Não representa uma porcentagem de “causalidade” ou garantia de previsão.</p><p>Covariância amostral: <strong>{precise(data.modelo.covariancia)}</strong>.</p></div></ChartCard></div></div>
 <div className="section-space"><InfoBox tone="warning" title="Correlação não implica causalidade.">Municípios maiores podem movimentar valores e quantidades maiores. Não foram estimados efeitos causais, intervalos de confiança ou p-valores. Observações repetidas no tempo exigiriam um tratamento próprio para inferência.</InfoBox></div><ChartCard title="Resíduos do ajuste" subtitle="X × (Y observado − Y estimado). Padrões e dispersão crescente sinalizam limitações da reta." className="section-space"><RegressionChart data={data} residuals/></ChartCard></>}</>;
}
