"use client";
import {useState} from "react";
import {Play} from "../ui/icons";
import {useLab,useAnalysis} from "../lab-context";
import {useResource} from "@/lib/api";
import {PageHeading,FilterBar,VariableSelect,Metric,ChartCard,Status,InfoBox} from "../shared";
import {Card} from "../ui/card";
import {Input,Label,Select} from "../ui/input";
import {Button} from "../ui/button";
import {Histogram,LLNChart} from "../charts";
import {precise,number} from "@/lib/utils";
import type {LLN,CLT} from "@/lib/types";
function LLNPanel(){const [experiment,setExperiment]=useState("moeda"),[repeats,setRepeats]=useState(2000),[outcome,setOutcome]=useState(1),[seed,setSeed]=useState(42),[submitted,setSubmitted]=useState<object|null>(null);const query=useResource<LLN>("simulacoes/lgn",submitted??undefined,submitted!==null);const data=query.data;
 function run(){const body={experimento:experiment,repeticoes:repeats,resultado:outcome,semente:seed};setSubmitted(body);query.retry();}
 return <><Card className="control-card"><div className="controls"><div className="control-field"><Label htmlFor="experimento">Experimento</Label><Select id="experimento" value={experiment} onChange={event=>{setExperiment(event.target.value);setOutcome(1);}}><option value="moeda">Moeda justa</option><option value="dado">Dado justo de seis faces</option></Select></div><div className="control-field small-field"><Label htmlFor="resultado">Resultado observado</Label><Select id="resultado" value={outcome} onChange={event=>setOutcome(Number(event.target.value))}>{(experiment==="moeda"?[1,2]:[1,2,3,4,5,6]).map(value=><option key={value} value={value}>{experiment==="moeda"?(value===1?"Cara":"Coroa"):value}</option>)}</Select></div><div className="control-field small-field"><Label htmlFor="repeticoes-lgn">Repetições</Label><Input id="repeticoes-lgn" type="number" min={10} max={100000} value={repeats} onChange={event=>setRepeats(Number(event.target.value))}/></div><div className="control-field small-field"><Label htmlFor="semente-lgn">Semente</Label><Input id="semente-lgn" type="number" min={0} max={2147483647} value={seed} onChange={event=>setSeed(Number(event.target.value))}/></div><Button onClick={run} disabled={query.loading}><Play size={14}/>Executar simulação</Button></div><p className="control-note">Até 100.000 experimentos. Mesma semente e mesmos parâmetros reproduzem a sequência. Não depende da disponibilidade do BCB.</p></Card>
 <Status {...query} onRetry={query.retry}/>{!submitted&&<InfoBox title="O acaso em perspectiva">Execute o experimento para observar a frequência acumulada se aproximar da probabilidade teórica. Aproximação não significa convergência monotônica.</InfoBox>}{data&&!query.loading&&!query.error&&<><div className="metrics-grid"><Metric label="Probabilidade teórica" value={precise(data.probabilidade)}/><Metric label="Frequência final" value={precise(data.frequencia_final)} accent/><Metric label="Ocorrências do evento" value={number(data.acertos,0)}/><Metric label="Repetições" value={number(data.repeticoes,0)} hint={`Semente: ${data.semente}`}/></div><ChartCard title="Convergência da frequência relativa" subtitle="Experimentos acumulados × frequência relativa"><LLNChart data={data}/><div className="legend"><span><i/>Frequência relativa</span><span><i className="theoretical"/>Probabilidade teórica</span></div></ChartCard><div className="section-space"><InfoBox>{data.aviso} A série visual é reduzida; todos os experimentos participam do resultado.</InfoBox></div></>}</>;
}
function CLTPanel(){const {filters}=useLab();const [variable,setVariable]=useState("quantidade_pagador_pf"),[size,setSize]=useState(30),[repeats,setRepeats]=useState(1000),[seed,setSeed]=useState(42),[submitted,setSubmitted]=useState<Record<string,unknown>|null>(null);
 const query=useAnalysis<CLT>("simulacoes/tcl",submitted??undefined,submitted!==null);const data=query.data?.resultado;const filterChanged=submitted!==null&&Object.keys(filters).some(key=>submitted[key]!==filters[key as keyof typeof filters]);
 function run(){setSubmitted({...filters,variavel:variable,tamanho_amostra:size,repeticoes:repeats,semente:seed});query.retry();}
 return <><FilterBar/><Card className="control-card"><div className="controls"><VariableSelect value={variable} onChange={setVariable}/><div className="control-field small-field"><Label htmlFor="tamanho">Tamanho da amostra (n)</Label><Input id="tamanho" type="number" min={2} max={1000} value={size} onChange={event=>setSize(Number(event.target.value))}/></div><div className="control-field small-field"><Label htmlFor="repeticoes-tcl">Número de amostras</Label><Input id="repeticoes-tcl" type="number" min={50} max={10000} value={repeats} onChange={event=>setRepeats(Number(event.target.value))}/></div><div className="control-field small-field"><Label htmlFor="semente-tcl">Semente</Label><Input id="semente-tcl" type="number" min={0} max={2147483647} value={seed} onChange={event=>setSeed(Number(event.target.value))}/></div><Button onClick={run} disabled={query.loading||size*repeats>2000000}><Play size={14}/>Executar simulação</Button></div><div className="inline section-space"><span className="small muted">Compare tamanhos:</span>{[5,30,100].map(value=><Button key={value} size="sm" variant={size===value?"secondary":"outline"} onClick={()=>setSize(value)}>n = {value}</Button>)}<span className="small muted">Sorteios com reposição · limite de 2 milhões por execução</span></div></Card>
 {size*repeats>2000000&&<InfoBox tone="warning">Reduza o tamanho ou as repetições: o produto deve ser no máximo 2.000.000.</InfoBox>}{filterChanged&&<InfoBox tone="warning">Os filtros foram alterados. Execute novamente para atualizar a simulação; abaixo permanece o resultado do recorte anterior.</InfoBox>}
 <Status {...query} onRetry={query.retry}/>{!submitted&&<InfoBox title="Uma distribuição de médias">Cada simulação sorteia n observações do recorte e calcula sua média. A distribuição empírica é a população do experimento, não uma amostra representativa de pessoas.</InfoBox>}
 {data&&!query.loading&&!query.error&&<><div className="metrics-grid"><Metric label="Média da população" value={precise(data.media_populacao)}/><Metric label="Média das médias" value={precise(data.media_das_medias)} accent/><Metric label="Desvio das médias" value={precise(data.desvio_das_medias)} hint="Desvio amostral da simulação"/><Metric label="Erro padrão teórico" value={precise(data.erro_padrao)} hint="σ / √n"/></div><div className="two-columns"><ChartCard title="Distribuição original" subtitle="Valores município-mês no universo selecionado"><Histogram bins={data.histograma_original} density/></ChartCard><ChartCard title="Distribuição das médias amostrais" subtitle={`n = ${data.tamanho_amostra} · ${number(data.repeticoes,0)} amostras · semente ${data.semente}`}><Histogram bins={data.histograma_medias} curve={data.curva} density/></ChartCard></div><div className="section-space"><InfoBox title="Interpretando o Teorema Central do Limite">{data.aviso} Não há garantia universal de aproximação satisfatória em n = 30, especialmente com caudas longas. A curva usa a média do universo e σ/√n, não um ajuste arbitrário às simulações.</InfoBox></div></>}</>;
}
export function SimulationPage(){const [tab,setTab]=useState("tcl");return <><PageHeading title="Probabilidade e Simulação" description="Experimente os fundamentos da probabilidade com Monte Carlo. Controle os parâmetros, repita o experimento e observe a matemática acontecer."/><div className="tabs" role="tablist" aria-label="Experimento"><button role="tab" aria-selected={tab==="lgn"} className={tab==="lgn"?"active":""} onClick={()=>setTab("lgn")}>Lei dos Grandes Números</button><button role="tab" aria-selected={tab==="tcl"} className={tab==="tcl"?"active":""} onClick={()=>setTab("tcl")}>Teorema Central do Limite</button></div>{tab==="lgn"?<LLNPanel/>:<CLTPanel/>}</>;}
