"use client";
import {useId} from "react";
import {ResponsiveContainer,AreaChart,Area,CartesianGrid,XAxis,YAxis,Tooltip,BarChart,Bar,LineChart,Line,ReferenceLine,ScatterChart,Scatter,PieChart,Pie,Cell} from "recharts";
import {compact,money,number,period,precise} from "@/lib/utils";
import type {Bin,Curve,Box,Panorama,LLN,Regression,Category,Distribution} from "@/lib/types";
const teal="var(--primary)",blue="var(--blue)",grid="var(--border)";
const tooltipStyle={background:"var(--surface)",border:"1px solid var(--border)",borderRadius:6,color:"var(--ink)",fontSize:11};
const tick={fontSize:10,fill:"var(--muted)"};
/** Apenas converte valores do servidor em coordenadas; não estima parâmetros. */
export function Histogram({bins,curve=[],title="Distribuição observada",density=false}:{bins:Bin[];curve?:Curve;title?:string;density?:boolean}){
 const id=useId();if(!bins.length)return <p>Não há classes.</p>;
 const w=740,h=305,l=66,r=22,t=22,b=52;
 const min=Math.min(bins[0].inferior,...curve.map(point=>point.valor)),max=Math.max(bins[bins.length-1].superior,...curve.map(point=>point.valor));
 const peak=Math.max(...bins.map(bin=>density?bin.densidade:bin.frequencia),...curve.map(point=>point.densidade),1e-30)*1.12;
 const x=(value:number)=>l+(value-min)/(max-min||1)*(w-l-r),y=(value:number)=>h-b-value/peak*(h-t-b);
 return <><svg viewBox={`0 0 ${w} ${h}`} className="svg-chart" role="img" aria-labelledby={id}><title id={id}>{title}. {bins.length} classes; {density?"eixo vertical de densidade":"eixo vertical de frequência"}. Consulte a tabela para valores exatos.</title>
 {[0,1,2,3,4].map(i=><g key={i}><line x1={l} x2={w-r} y1={y(peak*i/4)} y2={y(peak*i/4)} stroke={grid} strokeDasharray="3 5"/><text x={l-9} y={y(peak*i/4)+3} textAnchor="end">{density?precise(peak*i/4):compact(peak*i/4)}</text></g>)}
 {bins.map((bin,i)=><rect key={i} x={x(bin.inferior)+.6} y={y(density?bin.densidade:bin.frequencia)} width={Math.max(.3,x(bin.superior)-x(bin.inferior)-1.2)} height={h-b-y(density?bin.densidade:bin.frequencia)} fill={teal} opacity=".75" rx="1"><title>{number(bin.inferior)} a {number(bin.superior)}: {number(bin.frequencia,0)} observações; densidade {precise(bin.densidade)}</title></rect>)}
 {curve.length>0&&<polyline fill="none" stroke={blue} strokeWidth="2.5" points={curve.map(point=>`${x(point.valor)},${y(point.densidade)}`).join(" ")}/>}
 {[0,1,2,3,4].map(i=><text key={i} x={x(min+(max-min)*i/4)} y={h-b+22} textAnchor="middle">{compact(min+(max-min)*i/4)}</text>)}
 <text x={(w+l-r)/2} y={h-7} textAnchor="middle">Valor observado</text><text x={l} y={12}>{density?"Densidade":"Frequência absoluta"}</text></svg>
 {curve.length>0&&<div className="legend"><span><i/>Dados observados (densidade)</span><span><i className="theoretical"/>Distribuição teórica</span></div>}</>;
}
/** Boxplot recebe quartis, limites e bigodes pré-calculados pela API. */
export function BoxPlot({box}:{box:Box}){
 const id=useId(),low=Math.min(box.bigode_inferior,...box.valores),high=Math.max(box.bigode_superior,...box.valores);const x=(n:number)=>50+(n-low)/(high-low||1)*635;
 return <><svg className="svg-chart" viewBox="0 0 740 180" role="img" aria-labelledby={id}><title id={id}>Boxplot: Q1 {number(box.q1)}, mediana {number(box.q2)}, Q3 {number(box.q3)}. {number(box.quantidade,0)} atípicos.</title><line x1="50" x2="685" y1="129" y2="129" stroke={grid}/>
 <line x1={x(box.bigode_inferior)} x2={x(box.bigode_superior)} y1="68" y2="68" stroke={teal}/>{[box.bigode_inferior,box.bigode_superior].map((n,i)=><line key={i} x1={x(n)} x2={x(n)} y1="46" y2="90" stroke={teal} strokeWidth="2"/>)}
 <rect x={x(box.q1)} y="36" width={Math.max(1,x(box.q3)-x(box.q1))} height="64" fill="var(--mint)" stroke={teal}/><line x1={x(box.q2)} x2={x(box.q2)} y1="36" y2="100" stroke={teal} strokeWidth="3"/>
 {box.valores.map((n,i)=><circle key={i} cx={x(n)} cy={68+(i%5-2)*6} r="2.4" fill={blue} opacity=".45"><title>Atípico: {number(n)}</title></circle>)}
 {[0,1,2,3,4].map(i=><text key={i} x={50+i*635/4} y="151" textAnchor="middle">{compact(low+(high-low)*i/4)}</text>)}</svg><p className="chart-caption">Bigodes: valores observados dentro de Q1 − 1,5 × IQR e Q3 + 1,5 × IQR. Atípicos não são excluídos. Até 500 pontos desenhados, sem alterar os cálculos.</p></>;
}
export function EvolutionChart({data,metric}:{data:Panorama["meses"];metric:"valor"|"quantidade"}){const id=useId().replaceAll(":","");return <div className="chart-container"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{left:10,right:10,top:14,bottom:8}}><defs><linearGradient id={id} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={teal} stopOpacity={.18}/><stop offset="100%" stopColor={teal} stopOpacity={.01}/></linearGradient></defs><CartesianGrid stroke={grid} strokeDasharray="3 5" vertical={false}/><XAxis dataKey="competencia" tickFormatter={period} tick={tick} axisLine={false} tickLine={false}/><YAxis tickFormatter={compact} tick={tick} axisLine={false} tickLine={false} width={55}/><Tooltip contentStyle={tooltipStyle} labelFormatter={value=>period(String(value))} formatter={value=>[metric==="valor"?money(Number(value)):number(Number(value)),metric==="valor"?"Valor (R$)":"Transações"]}/><Area type="linear" dataKey={metric} stroke={teal} strokeWidth={2.5} fill={`url(#${id})`} dot={{r:3,fill:teal}} isAnimationActive={false}/></AreaChart></ResponsiveContainer></div>;}
export function RegionsChart({data,metric}:{data:Panorama["regioes"];metric:"valor"|"quantidade"}){return <div className="chart-container short"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} layout="vertical" margin={{left:0,right:20,top:8,bottom:0}}><CartesianGrid stroke={grid} horizontal={false} strokeDasharray="3 5"/><XAxis type="number" tickFormatter={compact} tick={tick} axisLine={false} tickLine={false}/><YAxis type="category" dataKey="regiao" width={96} tick={tick} axisLine={false} tickLine={false}/><Tooltip contentStyle={tooltipStyle} formatter={value=>[number(Number(value)),metric==="valor"?"Valor (R$)":"Transações"]}/><Bar dataKey={metric} fill={teal} radius={[0,4,4,0]} barSize={23} isAnimationActive={false}/></BarChart></ResponsiveContainer></div>;}
export function PeopleChart({data,metric}:{data:Panorama["pessoas"];metric:"valor"|"quantidade"}){return <div className="chart-container short"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} margin={{left:0,right:15,top:12,bottom:0}}><CartesianGrid stroke={grid} vertical={false} strokeDasharray="3 5"/><XAxis dataKey="pessoa" tickFormatter={value=>String(value).toLowerCase()==="pf"?"Pessoa Física":"Pessoa Jurídica"} tick={tick} axisLine={false} tickLine={false}/><YAxis tickFormatter={compact} tick={tick} width={62} axisLine={false} tickLine={false}/><Tooltip contentStyle={tooltipStyle} formatter={value=>[number(Number(value)),metric==="valor"?"Valor (R$)":"Transações"]}/><Bar dataKey={metric} radius={[5,5,0,0]} barSize={70} isAnimationActive={false}>{data.map((entry,index)=><Cell key={entry.pessoa} fill={index===0?teal:blue}/>)}</Bar></BarChart></ResponsiveContainer></div>;}
export function CategoryChart({data,pie=false}:{data:Category[];pie?:boolean}){const showPie=pie&&data.length<=6;const shown=showPie?data:data.slice(0,20);return <div className="chart-container"><ResponsiveContainer width="100%" height="100%">{showPie?<PieChart><Pie data={shown} dataKey="frequencia" nameKey="categoria" innerRadius={60} outerRadius={110} paddingAngle={2} isAnimationActive={false}>{shown.map((entry,index)=><Cell key={entry.categoria} fill={index%2?blue:teal} opacity={1-index*.025}/>)}</Pie><Tooltip contentStyle={tooltipStyle}/></PieChart>:<BarChart data={shown} margin={{left:0,right:12,bottom:35}}><CartesianGrid stroke={grid} vertical={false}/><XAxis dataKey="categoria" tick={tick} angle={-20} textAnchor="end" interval={0}/><YAxis tick={tick}/><Tooltip contentStyle={tooltipStyle}/><Bar dataKey="frequencia" name="Frequência" fill={teal} isAnimationActive={false}/></BarChart>}</ResponsiveContainer><p className="chart-caption">{showPie?"Todas as categorias estão representadas; o total corresponde a 100%.":`${pie?"Pizza indisponível para mais de seis categorias; exibindo barras. ":""}Gráfico limitado às primeiras 20 categorias, sem renormalizar frequências. A tabela contém todas.`}</p></div>;}
export function LLNChart({data}:{data:LLN}){return <div className="chart-container tall"><ResponsiveContainer width="100%" height="100%"><LineChart data={data.pontos} margin={{left:6,right:18,top:15,bottom:12}}><CartesianGrid stroke={grid} strokeDasharray="3 5"/><XAxis dataKey="repeticao" type="number" domain={[1,data.repeticoes]} tickFormatter={compact} tick={tick}/><YAxis domain={[0,1]} tick={tick}/><Tooltip contentStyle={tooltipStyle} formatter={value=>[number(Number(value),5),"Frequência relativa"]}/><ReferenceLine y={data.probabilidade} stroke={blue} strokeDasharray="6 4"/><Line type="linear" dataKey="frequencia" stroke={teal} dot={false} strokeWidth={1.7} isAnimationActive={false}/></LineChart></ResponsiveContainer></div>;}
export function RegressionChart({data,residuals=false}:{data:Regression;residuals?:boolean}){return <div className={`chart-container ${residuals?"":"tall"}`}><ResponsiveContainer width="100%" height="100%"><ScatterChart margin={{left:12,right:16,top:14,bottom:10}}><CartesianGrid stroke={grid} strokeDasharray="3 5"/><XAxis type="number" dataKey="valor_x" name="X" tickFormatter={compact} tick={tick}/><YAxis type="number" dataKey={residuals?"residuo":"valor_y"} name={residuals?"Resíduo":"Y"} tickFormatter={compact} tick={tick} width={65}/><Tooltip content={({active,payload})=>{if(!active||!payload?.length)return null;const point=payload[0]?.payload;return <div className="chart-tooltip"><strong>{point.municipio??"Reta estimada"} {point.uf??""}</strong><p>{point.competencia?period(point.competencia):""}</p><p>X: {number(point.valor_x)}<br/>{residuals?"Resíduo":"Y"}: {number(residuals?point.residuo:point.valor_y)}</p></div>;}}/><Scatter data={data.pontos} fill={teal} fillOpacity={.4} isAnimationActive={false}/>{residuals?<ReferenceLine y={0} stroke={blue}/>:<Scatter data={data.reta} fill={blue} line={{stroke:blue,strokeWidth:2}} isAnimationActive={false}/>}</ScatterChart></ResponsiveContainer></div>;}
export function MassChart({data}:{data:Distribution}){const observed=data.observados??[],curve=data.curva;const id=useId();const minimum=Math.min(...observed.map(p=>p.valor),...curve.map(p=>p.valor)),maximum=Math.max(...observed.map(p=>p.valor),...curve.map(p=>p.valor)),peak=Math.max(...observed.map(p=>p.probabilidade),...curve.map(p=>p.densidade),1e-10)*1.1;const x=(n:number)=>60+(n-minimum)/(maximum-minimum||1)*640,y=(n:number)=>255-n/peak*225;
return <><svg className="svg-chart" viewBox="0 0 740 305" role="img" aria-labelledby={id}><title id={id}>Probabilidades observadas e massa da distribuição de Poisson. Valores inteiros; sem curva de densidade contínua.</title>{[0,1,2,3,4].map(i=><g key={i}><line x1="60" x2="700" y1={y(peak*i/4)} y2={y(peak*i/4)} stroke={grid}/><text x="51" y={y(peak*i/4)+3} textAnchor="end">{precise(peak*i/4)}</text><text x={60+i*160} y="280" textAnchor="middle">{compact(minimum+(maximum-minimum)*i/4)}</text></g>)}{observed.map((point,i)=><line key={i} x1={x(point.valor)} x2={x(point.valor)} y1="255" y2={y(point.probabilidade)} stroke={teal} strokeWidth="2"><title>{point.valor}: {point.probabilidade}</title></line>)}{curve.map((point,i)=><circle key={i} cx={x(point.valor)} cy={y(point.densidade)} r="2.5" fill={blue}><title>Poisson P(X={point.valor})={point.densidade}</title></circle>)}<text x="60" y="12">Massa de probabilidade</text></svg><div className="legend"><span><i/>Frequência relativa observada</span><span><i className="theoretical"/>Poisson (pontos inteiros)</span></div></>;
}

